### PR TITLE
Courses Endpoint Docs

### PR DESCRIPTION
**Pull request by uniphil**
Started some basic docs for an endpoint for courses. Does this make sense?

### CODE REVIEW

**Comment by uniphil** [comment]
I was thinking of doing a pull request for each endpoint (so I'm not suggesting we skip out on search with this!), but maybe big-picture all-endpoints design should be in one place (this issue/pull req/whatever)?

**Comment by mystor** [comment]
I think opening a new issue called something like "Big Picture" would probably be a good idea

**Comment by Graham42** [comment]
can this pull request be closed since we have another issue discussing it?

**Comment by uniphil** [comment]
Don't see why not

**Pull request closed without merging**
